<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <AssemblyName>ClamAVGuardian</AssemblyName>
    <RootNamespace>ClamAVGuardian</RootNamespace>
    <Version>1.2.5.2</Version>
    <ApplicationIcon>Resources\AppIcon.ico</ApplicationIcon>

    <!-- Single-file, self-contained publish settings -->
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StreamJsonRpc" Version="2.19.27" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClamAVGuardian.Core\ClamAVGuardian.Core.csproj" />
  </ItemGroup>

</Project>
